[package]
name = "chip8emu"
version = "0.1.0"
authors = ["Nicolas Antinori <nicolas_antinori@hotmail.com>"]

[dependencies]
rand = "0.8"
termion = "2.0"
linux_raw_input_rs = "0.1.6"
clap = "3"

[dependencies.sdl2]
version = "0.30"
default-features = false
features = ["gfx"]
